spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_list
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: todo_list
      password: todo_list
  jpa:
    show-sql: true