CREATE DATABASE todo_list;

CREATE USER todo_list@'%' IDENTIFIED BY 'todo_list';

GRANT ALL PRIVILEGES ON todo_list.* TO todo_list@'%';

USE todo_list;

CREATE TABLE user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nickname VARCHAR(200) NULL,
    login_id VARCHAR(200) NOT NULL UNIQUE,
    status SMALLINT(1) NOT NULL DEFAULT 1,
    password VARCHAR(60) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE todo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    user_id INT NOT NULL,
    due_date DATE NULL,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_todo_user_id FOREIGN KEY (`user_id`) REFERENCES user(`id`)
);